Update d2scfEX_d.yml

diff --git a/.github/workflows/d2scfEX_d.yml b/.github/workflows/d2scfEX_d.yml
--- a/.github/workflows/d2scfEX_d.yml
+++ b/.github/workflows/d2scfEX_d.yml
@@ -82,8 +82,8 @@ jobs:
           if [[ ! -z $TENCENT_MEMORYSIZE ]]; then sed -i -E 's/memorySize:[^\n]+/memorySize: '"$TENCENT_MEMORYSIZE"'/' serverless.yml; fi;
           if [[ ! -z $TENCENT_TIMEOUT ]]; then sed -i -E 's/timeout:[^\n]+/timeout: '"$TENCENT_TIMEOUT"'/' serverless.yml; fi;
           if [[ ! -z $TENCENT_RUNTIME ]]; then sed -i -E 's/runtime:[^\n]+/runtime: '"$TENCENT_RUNTIME"'/' serverless.yml; fi;
-          sed -i '/timeout:/a eip: true' serverless.yml; 
-          sed -i '/timeout:/a publicAccess: true' serverless.yml; 
+          sed -i '/timeout:/a   eip: true' serverless.yml; 
+          sed -i '/timeout:/a   publicAccess: true' serverless.yml; 
           while read line;do
             echo "      $line" >> serverless.yml
           done < ../config.yml
@@ -101,7 +101,7 @@ jobs:
       #     echo 'require("./sendNotify").sendNotify("仓库非私有!","配置文件部署方式仓库必须为私有!(如已经私有请忽略并反馈Issues,感谢!)")' > notify.js
       #     node notify.js
       #     rm -rf notify.js
-#       - name: deploy
-#         working-directory: ./JD_tencent_scf
-#         run: |
-#           slt deploy --debug && echo 'Deploy Success' || (echo 'Deploy Failed'; echo 'require("./sendNotify").sendNotify("云函数部署异常！请重试","点击通知，登入后查看详情",{ url: process.env.GITHUB_SERVER_URL + "/" + process.env.GITHUB_REPOSITORY + "/actions/runs/" + process.env.GITHUB_RUN_ID + "?check_suite_focus=true" })' > notify.js; node notify.js; exit 1)
+      - name: deploy
+        working-directory: ./JD_tencent_scf
+        run: |
+          slt deploy --debug && echo 'Deploy Success' || (echo 'Deploy Failed'; echo 'require("./sendNotify").sendNotify("云函数部署异常！请重试","点击通知，登入后查看详情",{ url: process.env.GITHUB_SERVER_URL + "/" + process.env.GITHUB_REPOSITORY + "/actions/runs/" + process.env.GITHUB_RUN_ID + "?check_suite_focus=true" })' > notify.js; node notify.js; exit 1)
