Update d2scfEX_d.yml

diff --git a/.github/workflows/d2scfEX_d.yml b/.github/workflows/d2scfEX_d.yml
--- a/.github/workflows/d2scfEX_d.yml
+++ b/.github/workflows/d2scfEX_d.yml
@@ -85,8 +85,8 @@ jobs:
           while read line;do
             echo "      $line" >> serverless.yml
           done < ../config.yml
-          # cat serverless.yml
-          # cat .env
+          cat serverless.yml
+          cat .env
           PUSH_VARIS=$(sed -r 's/(process.env.[a-z0-9A-Z\_]+)/\1\n/g' sendNotify.js | sed -rn 's/.*process.env.([a-z0-9A-Z\_]+).*/\1/p' | sort | uniq)
           parameter=$(tr "\n" "|" <<< $PUSH_VARIS)
           parameter=${parameter::-1}
@@ -99,7 +99,7 @@ jobs:
       #     echo 'require("./sendNotify").sendNotify("仓库非私有!","配置文件部署方式仓库必须为私有!(如已经私有请忽略并反馈Issues,感谢!)")' > notify.js
       #     node notify.js
       #     rm -rf notify.js
-      - name: deploy
-        working-directory: ./JD_tencent_scf
-        run: |
-          slt deploy --debug && echo 'Deploy Success' || (echo 'Deploy Failed'; echo 'require("./sendNotify").sendNotify("云函数部署异常！请重试","点击通知，登入后查看详情",{ url: process.env.GITHUB_SERVER_URL + "/" + process.env.GITHUB_REPOSITORY + "/actions/runs/" + process.env.GITHUB_RUN_ID + "?check_suite_focus=true" })' > notify.js; node notify.js; exit 1)
+#       - name: deploy
+#         working-directory: ./JD_tencent_scf
+#         run: |
+#           slt deploy --debug && echo 'Deploy Success' || (echo 'Deploy Failed'; echo 'require("./sendNotify").sendNotify("云函数部署异常！请重试","点击通知，登入后查看详情",{ url: process.env.GITHUB_SERVER_URL + "/" + process.env.GITHUB_REPOSITORY + "/actions/runs/" + process.env.GITHUB_RUN_ID + "?check_suite_focus=true" })' > notify.js; node notify.js; exit 1)
